
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 18297
 */
public class clientes extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    DefaultTableModel cliente;
    
      public clientes() {
        initComponents();
        this.cliente = (DefaultTableModel) tablacli.getModel();
        
        Mostrardatos("");
    }
      public void Limpiar(){
        try{
        txt_nom.setText("");
        txt_ape.setText("");
        txt_ced.setText("");
        txt_tel.setText("");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
           
           public void RefrescarTabla(){
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
        cliente.setColumnCount(0);
        cliente.setRowCount(0);
        tablacli.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            //Myconnection cc=new Myconnection();
            Connection cn=Myconnection.getconnection();
            RefrescarTabla();
            cliente.addColumn("idcliente");
            cliente.addColumn("nombre");
            cliente.addColumn("apellido");
            cliente.addColumn("cedula");
            cliente.addColumn("telefono");
         
            this.tablacli.setModel(cliente);
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM cliente";
            }
            else{
            sql="SELECT * FROM cliente WHERE cliente='"+valor+"'";
            } 

            String []datos=new String [5];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
           
            
     

            cliente.addRow(datos);
            }
            tablacli.setModel(cliente);
            }catch(SQLException ex){
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Titulo1co = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        txt_ape = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        txt_ced = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacli = new javax.swing.JTable();
        titulo2Clie = new javax.swing.JLabel();
        btn_insertar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        INcon = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 204, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 11, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1co.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Titulo1co.setText("Control Cliente:");
        jPanel1.add(Titulo1co, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, -1));

        Nombre.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Nombre.setText("Nombre:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(txt_ape, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 132, -1));

        Apellido.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Apellido.setText("Apellido:");
        jPanel1.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(txt_ced, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, -1));

        Cedula.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Cedula.setText("Cedula:");
        jPanel1.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel1.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        Telefono.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Telefono.setText("Telefono:");
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        tablacli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablacli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacli);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 56, 360, 230));

        titulo2Clie.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titulo2Clie.setText("Clientes");
        jPanel1.add(titulo2Clie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        btn_insertar.setText("INSERTAR");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 40));

        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 40));

        jButton3.setText("BORRRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 40));

        jButton4.setText("REPORTE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        INcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario.png"))); // NOI18N
        jPanel1.add(INcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tr.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        // TODO add your handling code here:
           String cli = txt_nom.getText();
        String ape = txt_ape.getText();
        String ced= txt_ced.getText();
        String tel= txt_tel.getText();
        
        
        PreparedStatement ps;
        String query = "INSERT INTO `cliente`(`nombre`,`apellido`,`cedula`,`telefono`) VALUES (?,?,?,?)";
        try {
            ps = Myconnection.getconnection().prepareStatement(query);
            

            ps.setString(1, cli);
            ps.setString(2, ape);
            ps.setString(3, ced);
            ps.setString(4, tel);
            
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Nuevo dato ingresado");
                Limpiar();
                Mostrardatos("");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }       
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Connection cn = Myconnection.getconnection();
        try {
          JasperReport jr = (JasperReport) JRLoader.loadObject(Producto.class.getResource("/Reporte/producto.jasper"));
          Map parametros = new HashMap<>();
          parametros.put("Titulo", "Reporte Productos");
            

          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp, false);
          jv.setVisible(true); 
        }  
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           String cli = txt_nom.getText();
        String ape = txt_ape.getText();
        String ced = txt_ced.getText();
        String tel = txt_tel.getText();
        String id = (String)cliente.getValueAt(tablacli.getSelectedRow(),0);
        

        

        PreparedStatement ps;
        String query = "UPDATE `cliente` SET `nombre`=?, `apellido`=?, `cedula`=?, `telefono"
                + ""
                + ""
                + ""
                + "`=?   WHERE `idcliente`=?";
        try {
            ps = Myconnection.getconnection().prepareStatement(query);
            
            ps.setString(5, id);
            ps.setString(1, cli);
            ps.setString(2, ape);
            ps.setString(3, ced);
            ps.setString(4, tel);
            
            

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, " producto Modificado");
            Limpiar();
            Mostrardatos("");

        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String id = (String)cliente.getValueAt(tablacli.getSelectedRow(),0);

        PreparedStatement ps;
        String query = "DELETE FROM `cliente` WHERE `idcliente`=?";
        try {
            ps = Myconnection.getconnection().prepareStatement(query);

            ps.setString(1, id);

            if(ps.executeUpdate() > 0)
            {

                JOptionPane.showMessageDialog(null, "producto Eliminado");
                Limpiar();
                Mostrardatos("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
                                         

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tablacliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacliMouseClicked
        // TODO add your handling code here:
        try{
  
          
            String cli = (String)cliente.getValueAt(tablacli.getSelectedRow(), 1);
            String ape = (String)cliente.getValueAt(tablacli.getSelectedRow(), 2);
            String ced = (String)cliente.getValueAt(tablacli.getSelectedRow(), 3);
            String tel = (String)cliente.getValueAt(tablacli.getSelectedRow(), 4);
            
                
            txt_nom.setText(cli);
            txt_ape.setText(ape);
            txt_ced.setText(ced);
            txt_tel.setText(tel);
           
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,"error"+ex);
        }
    }//GEN-LAST:event_tablacliMouseClicked

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel INcon;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Titulo1co;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacli;
    private javax.swing.JLabel titulo2Clie;
    private javax.swing.JTextField txt_ape;
    private javax.swing.JTextField txt_ced;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
