
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 18297
 */

public class usuario extends javax.swing.JFrame {

    
     DefaultTableModel usuario;
    
    public usuario() {
        initComponents();
        this.usuario = (DefaultTableModel) tablausu.getModel();
        
        Mostrardatos("");
    }
      public void Limpiar(){
        try{
        txt_usu.setText("");
        txt_cla.setText("");
        txt_cor.setText("");
        txt_nom.setText("");
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
           
           public void RefrescarTabla(){
        //Funcion encargada de Refrescar la tabla utilizando Revalidate
        try {
        usuario.setColumnCount(0);
        usuario.setRowCount(0);
        tablausu.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            //Myconnection cc=new Myconnection();
            Connection cn=Myconnection.getconnection();
            RefrescarTabla();
            usuario.addColumn("idusuario");
            usuario.addColumn("usuario");
            usuario.addColumn("clave");
            usuario.addColumn("correo");
            usuario.addColumn("nombre");
            usuario.addColumn("rol");
         
            this.tablausu.setModel(usuario);
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM usuario";
            }
            else{
            sql="SELECT * FROM usuario WHERE usuario='"+valor+"'";
            } 

            String []datos=new String [6];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            
     

            usuario.addRow(datos);
            }
            tablausu.setModel(usuario);
            }catch(SQLException ex){
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
 
    /**

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        Titulo1Con = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablausu = new javax.swing.JTable();
        Usuario = new javax.swing.JLabel();
        txt_usu = new javax.swing.JTextField();
        Rol = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        txt_cla = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_cor = new javax.swing.JTextField();
        btn_insertar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_reporte = new javax.swing.JButton();
        titulo2usu = new javax.swing.JLabel();
        txt_rol = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Correo1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1Con.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Titulo1Con.setText("Control de usuario");
        getContentPane().add(Titulo1Con, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        tablausu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablausu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablausuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablausu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 357, 247));

        Usuario.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        Usuario.setText("Usuario:");
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        getContentPane().add(txt_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 151, -1));

        Rol.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        Rol.setText("Rol:");
        getContentPane().add(Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        Clave.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        Clave.setText("Clave:");
        getContentPane().add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Nombre.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        Nombre.setText("Nombre:");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));
        getContentPane().add(txt_cla, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 151, -1));
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 151, -1));
        getContentPane().add(txt_cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 151, -1));

        btn_insertar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btn_insertar.setText("Insertar");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 39));

        btn_modificar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 39));

        btn_borrar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 39));

        btn_reporte.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btn_reporte.setText("Reporte");
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 90, 40));

        titulo2usu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titulo2usu.setText("Usuarios:");
        titulo2usu.setToolTipText("");
        getContentPane().add(titulo2usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 88, -1));
        getContentPane().add(txt_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 40, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/usuario.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Correo1.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        Correo1.setText("Correo:");
        getContentPane().add(Correo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tr.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        // este es el boton para insertar
      
        String usu = txt_usu.getText();
        String cla = txt_cla.getText();
        String cor = txt_cor.getText();
        String nom = txt_nom.getText();
        int rol = Integer.parseInt(txt_rol.getText());
        
        

        

        PreparedStatement ps;
        String query = "INSERT INTO `usuario`(`usuario`,`clave`,`correo`,`nombre`,rol`) VALUES (?,?,?,?,?)";
        try {
            ps = Myconnection.getconnection().prepareStatement(query);
            
            
            ps.setString(1, usu);
            ps.setString(2, cla);
            ps.setString(3, cor);
            ps.setString(4, nom);
            ps.setInt(5, rol);
          
         
            
            

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, " usuario insertado");
            Limpiar();
            Mostrardatos("");

        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        // TODO add your handling code here:
        
           Connection cn = Myconnection.getconnection();
        try {
          JasperReport jr = (JasperReport) JRLoader.loadObject(Producto.class.getResource("/Reporte/usuario.jasper"));
          Map parametros = new HashMap<>();
      
            

          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp, false);
          jv.setVisible(true); 
        }  
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btn_reporteActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
         // Este boton te sirve para actualizar el usuario
      
        String nom = txt_nom.getText();
        String usu = txt_usu.getText();
        String cla = txt_cla.getText();
        String cor = txt_cor.getText();
        int rol = Integer.parseInt(txt_rol.getText());
        String id = (String)usuario.getValueAt(tablausu.getSelectedRow(),0);
        
        PreparedStatement ps;
        String query = "UPDATE `usuario` SET `usuario`=?, `clave`=?, `correo`=?,`nombre`=?,`rol`=?  WHERE `idusuario`=?";
        try {
            ps = Myconnection.getconnection().prepareStatement(query);
            
           
            ps.setString(1, usu);
            ps.setString(2, cla);
            ps.setString(3, cor);
            ps.setString(4, nom);
            ps.setInt(5, rol);
            ps.setString(6, id);
         
            
            

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, " producto Modificado");
            Limpiar();
            Mostrardatos("");
           

        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // Este es el boton que sirve para borrar datos
       
        String id = (String)usuario.getValueAt(tablausu.getSelectedRow(),0);

        PreparedStatement ps;
        String query = "DELETE FROM `usuario` WHERE `idusuario`=?";
        try {
            ps = Myconnection.getconnection().prepareStatement(query);

            ps.setString(1, id);

            if(ps.executeUpdate() > 0)
            {

                JOptionPane.showMessageDialog(null, "producto Eliminado");
                Limpiar();
                Mostrardatos("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
                                         

    }//GEN-LAST:event_btn_borrarActionPerformed

    private void tablausuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablausuMouseClicked
        // para presentar los usuarios en los texfils
                try{
  
          
            String usu = (String)usuario.getValueAt(tablausu.getSelectedRow(), 1);
            String cla = (String)usuario.getValueAt(tablausu.getSelectedRow(), 2);
            String cor = (String)usuario.getValueAt(tablausu.getSelectedRow(), 3);
            String nom = (String)usuario.getValueAt(tablausu.getSelectedRow(), 4);
            String rol = (String)usuario.getValueAt(tablausu.getSelectedRow(), 5);
           
            
                
            txt_usu.setText(usu);
            txt_cla.setText(cla);
            txt_cor.setText(cor);
            txt_nom.setText(nom);
            txt_rol.setText(rol);
          
           
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,"error"+ex);
        }
       
    }//GEN-LAST:event_tablausuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Correo1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Rol;
    private javax.swing.JLabel Titulo1Con;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JTable tablausu;
    private javax.swing.JLabel titulo2usu;
    private javax.swing.JTextField txt_cla;
    private javax.swing.JTextField txt_cor;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_rol;
    private javax.swing.JTextField txt_usu;
    // End of variables declaration//GEN-END:variables
}
